### ISSUE TITLE
Cracking a BIP38 password, with many BIP38 samples

### ISSUE THREAD

**Issue by rterwedo** [bitcoinjs/bip38#37]
Given
1) a wallet.dat file with ~100 addresses.
2) 40 addresses in the same wallet, with addr, pub keys, encrypted private keys AND unencrypted private keys
3) mkey with: {crypted key, salt, and nDeriveIterations, etc)
4) Anything else we need from pywallet, etc

Read in a pwd file list, and compare to known values... to reverse engineer pwd?  Most tools assume someone does not have some of the unencrypted keys in the wallet.  Would be good for recovery...

We have come across a situation were we have some private keys but not all in a single encrypted wallet (backups) that used the same pwd.

**Comment by dcousens** [comment]
@rterwedo I suspect what you are asking is if there is a known plain text attack against BIP38?

With the assumptions that you have the plain-text AND cipher-text for a given private key.

**Comment by rterwedo** [comment]
@dcousens Essentially yes.  There are tools (such as btcrecover) where you can use these items to go after recovered wallets, but most everything I have seen assumes the wallet is 100% encrypted, or 100% complete (ie not corrupted).  A plain text attack would cover the middle ground, assuming its feasible.  (Is it in your estimation?) I am working on researching what would be the fastest setup to do this, given that a decent GPU setup of btcrecover can do ~1k-50k pwd / s.

**Comment by spongeeluv** [comment]
Hello i hope someone can help me please, basically i have made an offline paper wallet. lets bare in mind i have no printer or camera phone. Anyway i made the paper wallet offline.I deleted a few digits offline and wrote them down safely Came back online..cleared my browser and cache etc. I made a note of the public key..and sent funds from Paxful.com to my public key in my paper wallet. I even checked the transaction on block chain explorer it had been sent. Now i have my private key...Ive just read it should always start with a number 5..well my private key does not start with a number 5. secondly it seems longer than my public key. what i want to know is can i withdraw or spend or send out again or have i lost them because i never scanned them?

**Comment by spongeeluv** [comment]
hello my name is mohammed ayyub. I'm interested in buying your business not just the domain name.
I have inquired and see that you have parked up your site on Afternic. If the business is not for sale could you please tell me your new website name.] I unfortunately have some bitcoin on a private key encrypted with bip38. Private key starting with 6P. iF YOU CAN HELP ME I WILL DONATE some bitcoin towards the cause. I also have a website (Bitgangstar.com) promoting bonafide bitcoin info etc. For your help i will give you 1NEEHJLFSdH3hggF77iaMXPAfuoVMuYA4g.....£43.21 Please check public key in Blockchain explorer or any bitcoin website you can check public key status. Status of the key is unspent. You can spend providing you have private key and Paraphase. Thankyou hope to hear from you soon.


p.s(I'm too embarrassed to tell you how much bitcoin i have on  a previous bip38 encrypted private key address ) boohoo.. :(

**Comment by aironmanne** [comment]
spongeluv, I can try to help you if you'd like, I had a similar issue and built a tool to find my password. My email is fwhalbach@gmail.com
